# Generated by Django 2.2.24 on 2021-11-29 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211129_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='God',
            new_name='Post',
        ),
    ]
